name: simple flow

on: push

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout Repository
        uses: actions/checkout@v2
      
      - name: Step 2 - List Files
        run: ls -a

  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Step 1 - Checkout Repository
        uses: actions/checkout@v2

      - name: Step 2 - Print Working Directory
        run: pwd
