name: simple flow

on: push

  jobs:

    job1:
      name: First Job
      runs-on: ubunutu-latest
      steps:
        name: step 1 - some informative name
        uses: actions.checkout@.2
        name: step 2
        run: ls -a
    job2:
      name: Second Job
      runs-on: windows-latest
      steps: 
      names: step 1
      uses: actions.checkout@.2
      runs: pwd
